version: '3.3'
services:
  auth-service:
    image: library/joindb:latest
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    platform: linux/x86_64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1402
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
